import java.awt.image.BufferedImage;
import java.io.IOException;
import java.awt.Image;
import java.awt.image.PixelGrabber;
import java.io.InputStream;
import java.io.ByteArrayInputStream;
import javax.imageio.ImageIO;

// 
// Decompiled by Procyon v0.5.36
// 

public class Strings
{
    public static String fk;
    public static String an;
    public static String bt;
    public static String dt;
    public static String ch;
    public static String ab;
    public static String aq;
    public static String al;
    public static String ic;
    public static String aa;
    public static String ay;
    public static String ia;
    public static String av;
    public static String hm;
    public static String br;
    public static String ah;
    public static String is;
    public static String ar;
    public static String as;
    public static String de;
    public static String cj;
    public static String ak;
    public static String fw;
    public static String ad;
    public static String ae;
    public static String bm;
    public static String by;
    public static String bb;
    public static String bi;
    public static String be;
    public static String ht;
    public static String ms;
    public static String bo;
    public static String jy;
    public static String ep;
    public static String jo;
    public static String ij;
    static String bj;
    public static String dw;
    public static String bs;
    public static String gr;
    public static String bg;
    public static String bu;
    public static String az;
    public static String iy;
    public static String ba;
    public static String bv;
    public static String bl;
    public static String bp;
    public static String ai;
    public static String bh;
    public static String bw;
    public static String ce;
    public static String at;
    public static String jd;
    public static String cc;
    public static String hy;
    public static String ca;
    public static String mz;
    public static String fa;
    public static String cq;
    public static String cm;
    public static String cf;
    public static String gj;
    public static String cg;
    public static String cr;
    public static String du;
    public static String ap;
    public static String cv;
    public static String cb;
    public static String co;
    public static String cz;
    public static String it;
    public static String id;
    public static String jn;
    public static String ct;
    public static String cp;
    public static String cd;
    public static String hz;
    public static String lu;
    public static String dc;
    public static String do;
    public static String dm;
    public static String fv;
    public static String dl;
    public static String dk;
    public static String dx;
    public static String dv;
    public static String dz;
    public static String fd;
    public static String et;
    public static String dh;
    public static String dp;
    public static String fc;
    public static String db;
    public static String hg;
    public static String ma;
    public static String dd;
    public static String dj;
    public static String jg;
    public static String dn;
    public static String dy;
    public static String ds;
    public static String da;
    public static String hf;
    public static String eo;
    public static String eq;
    public static String hd;
    public static String ef;
    public static String dq;
    public static String gv;
    public static String ea;
    public static String eu;
    public static String aj;
    public static String eb;
    public static String el;
    public static String en;
    public static String ks;
    public static String eg;
    public static String ed;
    public static String ev;
    public static String em;
    public static String ew;
    public static String ex;
    public static String jw;
    public static String ao;
    public static String ey;
    public static String lx;
    public static String ei;
    public static String ee;
    public static String il;
    public static String ez;
    public static String field3226;
    public static String fh;
    public static String fl;
    public static String ho;
    public static String fo;
    public static String mx;
    public static String hv;
    public static String fb;
    public static String er;
    public static String fz;
    public static String fe;
    public static String fy;
    public static String cy;
    public static String fr;
    public static String my;
    public static String fq;
    public static String eh;
    public static String ff;
    public static String fj;
    public static String fg;
    public static String bk;
    public static String fm;
    public static String gg;
    public static String fu;
    public static String lz;
    public static String go;
    public static String gs;
    public static String af;
    public static String dg;
    public static String ge;
    public static String ga;
    public static String bz;
    public static String gu;
    public static String gh;
    public static String gy;
    public static String bd;
    public static String gw;
    public static String cn;
    public static String gf;
    public static String gm;
    public static String gi;
    public static String field3267;
    public static String gk;
    public static String gb;
    public static String gp;
    public static String gn;
    public static String fx;
    public static String ih;
    public static String gl;
    public static String ck;
    public static String hw;
    public static String hi;
    public static String hj;
    public static String gc;
    public static String hu;
    public static String hx;
    public static String ci;
    public static String bf;
    public static String hs;
    public static String hn;
    public static String hl;
    public static String hh;
    public static String hr;
    public static String hc;
    public static String am;
    public static String field3291;
    public static String jz;
    public static String hb;
    public static String hq;
    public static String cx;
    public static String hk;
    public static String ha;
    public static String hp;
    public static String he;
    public static String bc;
    public static String cu;
    public static String if;
    public static String gt;
    public static String iu;
    public static String ej;
    public static String iw;
    public static String iz;
    public static String ie;
    public static String iq;
    public static String fp;
    public static String ik;
    public static String in;
    public static String bn;
    public static String ii;
    public static String gx;
    public static String bq;
    public static String dr;
    public static String iv;
    public static String ir;
    public static String io;
    public static String ip;
    public static String mq;
    public static String ig;
    public static String ky;
    public static String lk;
    public static String ix;
    public static String fn;
    public static String kz;
    public static String es;
    public static String ib;
    public static String jx;
    public static String im;
    public static String jk;
    public static String jq;
    public static String je;
    public static String jj;
    public static String jm;
    public static String jv;
    public static String gz;
    public static String jf;
    public static String jc;
    public static String js;
    public static String jr;
    public static String lb;
    public static String ek;
    public static String aw;
    public static String jp;
    public static String jt;
    public static String ja;
    public static String jb;
    public static String ji;
    public static String ju;
    public static String jl;
    public static String kc;
    public static String ku;
    public static String ke;
    public static String df;
    public static String kh;
    public static String kp;
    public static String kf;
    public static String ec;
    public static String kn;
    public static String ag;
    public static String km;
    public static String lv;
    public static String lm;
    public static String lg;
    public static String ls;
    public static String lf;
    public static String li;
    public static String cw;
    public static String gd;
    public static String lh;
    public static String ft;
    public static String cl;
    public static String field3376;
    public static String ln;
    public static String lt;
    public static String mm;
    public static String lc;
    public static String ld;
    public static String lq;
    public static String lj;
    public static String ll;
    public static String le;
    public static String bx;
    public static String ac;
    public static String lo;
    public static String lw;
    public static String lr;
    public static String mt;
    public static String mw;
    public static String au;
    public static String mu;
    public static String di;
    public static String mv;
    public static String me;
    public static String cs;
    public static String ax;
    public static String jh;
    public static String mp;
    public static String mj;
    public static String gq;
    public static String mc;
    public static String mh;
    public static String mg;
    public static String mo;
    public static String mn;
    public static String mi;
    public static String md;
    public static String mr;
    public static String ml;
    public static String mf;
    public static String fs;
    public static String mk;
    public static String mb;
    public static String nz;
    public static String nw;
    public static String ns;
    
    Strings() throws Throwable {
        throw new Error();
    }
    
    static {
        Strings.af = "Members object";
        Strings.an = "Take";
        Strings.aw = "Drop";
        Strings.ac = "Hidden";
        Strings.au = "Ok";
        Strings.ab = "Select";
        Strings.aq = "Continue";
        Strings.al = "Discard";
        Strings.at = "null";
        Strings.aa = "Trust this computer";
        Strings.ay = "for 30 days: ";
        Strings.ao = "Loading - please wait.";
        Strings.ax = "Connection lost";
        Strings.ai = "Please wait - attempting to reestablish";
        Strings.ag = "Starting game engine...";
        Strings.ah = "Prepared visibility map";
        Strings.av = "Connecting to update server";
        Strings.ar = "Checking for updates - ";
        Strings.am = "Loaded update list";
        Strings.as = "Prepared sound engine";
        Strings.aj = "Loading fonts - ";
        Strings.ak = "Loaded fonts";
        Strings.az = "Loading title screen - ";
        Strings.ad = "Loaded title screen";
        Strings.ae = "Loading config - ";
        Strings.ap = "Loaded config";
        Strings.by = "Loading sprites - ";
        Strings.bb = "Loaded sprites";
        Strings.bi = "Loading textures - ";
        Strings.be = "Loaded textures";
        Strings.bk = "Loaded input handler";
        Strings.bx = "Loading wordpack - ";
        Strings.bo = "Loaded wordpack";
        Strings.bz = "Loading interfaces - ";
        Strings.bm = "Loaded interfaces";
        Strings.bd = "Loading world map - ";
        Strings.bt = "Loaded world map";
        Strings.bj = "Please visit the support page for assistance.";
        Strings.bn = "View Appeal Options";
        Strings.bs = "Recover Account";
        Strings.br = "";
        Strings.bg = "Please enter a 6-digit PIN.";
        Strings.bu = "";
        Strings.bf = "You have only just left another world.";
        Strings.bq = "Your profile will be transferred in:";
        Strings.ba = " seconds.";
        Strings.bv = "Connection timed out.";
        Strings.bl = "Please try using a different world.";
        Strings.bp = "";
        Strings.bc = "Error connecting to server.";
        Strings.bh = "Please try using a different world.";
        Strings.bw = "";
        Strings.ce = "No response from server.";
        Strings.ci = "Please try using a different world.";
        Strings.cs = "";
        Strings.cc = "Your account has been involved";
        Strings.cn = "in serious rule breaking.";
        Strings.ca = "";
        Strings.cu = "Either your account is still logged in, or the last";
        Strings.ck = "world you were using has become unavailable.";
        Strings.cq = "Please try again later.";
        Strings.cm = "RuneScape has been updated!";
        Strings.cf = "Please reload this page.";
        Strings.cl = "";
        Strings.cg = "This world is full.";
        Strings.cr = "Please use a different world.";
        Strings.cy = "";
        Strings.cx = "Unable to connect.";
        Strings.cv = "Login server offline.";
        Strings.cb = "";
        Strings.co = "Login limit exceeded.";
        Strings.cz = "Too many connections from your address.";
        Strings.cw = "";
        Strings.cj = "Unable to connect.";
        Strings.ch = "Bad session id.";
        Strings.ct = "";
        Strings.cp = "We suspect someone knows your password.";
        Strings.cd = "Press 'change your password' on front page.";
        Strings.dm = "";
        Strings.dw = "You need a members account to login to this world.";
        Strings.dc = "Please subscribe, or use a different world.";
        Strings.do = "";
        Strings.di = "Could not complete login.";
        Strings.dr = "Please try using a different world.";
        Strings.dl = "";
        Strings.dk = "The server is being updated.";
        Strings.dt = "Please wait 1 minute and try again.";
        Strings.dv = "";
        Strings.dz = "Too many login attempts.";
        Strings.dg = "You can use the Jagex Launcher to continue playing.";
        Strings.de = "Press the button below to download it now.";
        Strings.dh = "To access this free world, log into a";
        Strings.dp = "members world and move your character";
        Strings.du = "to a non-members area.";
        Strings.db = "Your account has been locked due to";
        Strings.df = "suspicious activity.";
        Strings.dq = "Please recover your account.";
        Strings.dd = "This world is running a closed Beta.";
        Strings.dj = "Sorry invited players only.";
        Strings.dx = "Please use a different world.";
        Strings.dn = "Invalid loginserver requested.";
        Strings.dy = "Please try using a different world.";
        Strings.ds = "";
        Strings.da = "Malformed login packet.";
        Strings.ep = "Please try again.";
        Strings.eo = "";
        Strings.eq = "No reply from loginserver.";
        Strings.et = "Please wait 1 minute and try again.";
        Strings.ef = "";
        Strings.ez = "Error loading your profile.";
        Strings.ej = "Please contact customer support.";
        Strings.ea = "";
        Strings.eu = "Unexpected loginserver response.";
        Strings.es = "Please try using a different world.";
        Strings.eb = "";
        Strings.el = "This computers address has been blocked";
        Strings.en = "as it was used to break our rules.";
        Strings.er = "";
        Strings.eg = "";
        Strings.ed = "Service unavailable.";
        Strings.ev = "";
        Strings.em = "";
        Strings.ew = "Please enter your username/email address.";
        Strings.ex = "";
        Strings.eh = "";
        Strings.ek = "Please enter your password.";
        Strings.ey = "";
        Strings.ec = "Your account must have a displayname set";
        Strings.ei = "in order to play the game.  Please set it";
        Strings.ee = "via the website, or the main game.";
        Strings.fe = "The unpaid balance on your account needs";
        Strings.fs = "to be resolved before you can play.";
        Strings.field3226 = Strings.bj;
        Strings.fh = "Your account is currently inaccessible.";
        Strings.fl = "Please try again in a few minutes.";
        Strings.fp = "";
        Strings.fo = "You need to vote to play!";
        Strings.fx = "Visit runescape.com and vote,";
        Strings.fd = "and then come back here!";
        Strings.fb = "Sorry, but your account is not eligible to play.";
        Strings.fn = "For more information, please take a look at";
        Strings.fz = "our privacy policy.";
        Strings.fa = "Privacy Policy";
        Strings.fy = "Enter the 6-digit code generated by your";
        Strings.fw = "authenticator app.";
        Strings.fr = "";
        Strings.fv = "The code you entered was incorrect.";
        Strings.fq = "Please try again.";
        Strings.fc = "";
        Strings.ff = "Login attempt timed out.";
        Strings.fj = "Please try again.";
        Strings.fg = "";
        Strings.fk = "You were signed out.";
        Strings.fm = "Please sign in again.";
        Strings.ft = "";
        Strings.fu = "Failed to login.";
        Strings.gr = "Please try again.";
        Strings.go = "";
        Strings.gs = "Unexpected server response";
        Strings.gj = "Please try using a different world.";
        Strings.gg = "";
        Strings.ge = " has logged in.";
        Strings.ga = " has logged out.";
        Strings.gt = "Unable to find ";
        Strings.gu = "Use";
        Strings.gh = "Examine";
        Strings.gy = "Attack";
        Strings.gd = "Choose Option";
        Strings.gw = " more options";
        Strings.gc = "Walk here";
        Strings.gf = "level-";
        Strings.gm = "skill-";
        Strings.gi = "Please wait...";
        Strings.gq = "Close";
        Strings.gk = " ";
        Strings.gb = "M";
        Strings.gp = "M";
        Strings.gn = "K";
        Strings.gv = "K";
        Strings.gx = "World";
        Strings.gl = "Your friend list is full. Max of 200 for free users, and 400 for members";
        Strings.gz = " is already on your friend list";
        Strings.hw = "Your ignore list is full. Max of 100 for free users, and 400 for members";
        Strings.hi = " is already on your ignore list";
        Strings.hj = "You can't add yourself to your own friend list";
        Strings.hm = "You can't add yourself to your own ignore list";
        Strings.hu = "Please remove ";
        Strings.hx = " from your ignore list first";
        Strings.hd = "Please remove ";
        Strings.hv = " from your friend list first";
        Strings.hs = "yellow:";
        Strings.hn = "yellow:";
        Strings.hl = "red:";
        Strings.hh = "red:";
        Strings.hr = "green:";
        Strings.hc = "green:";
        Strings.hg = "cyan:";
        Strings.ho = "cyan:";
        Strings.ht = "purple:";
        Strings.hb = "purple:";
        Strings.hq = "white:";
        Strings.hz = "white:";
        Strings.hk = "flash1:";
        Strings.ha = "flash1:";
        Strings.hp = "flash2:";
        Strings.he = "flash2:";
        Strings.hf = "flash3:";
        Strings.hy = "flash3:";
        Strings.if = "glow1:";
        Strings.ia = "glow1:";
        Strings.iu = "glow2:";
        Strings.iw = "glow2:";
        Strings.iy = "glow3:";
        Strings.iz = "glow3:";
        Strings.ig = "wave:";
        Strings.ih = "wave:";
        Strings.il = "wave2:";
        Strings.is = "wave2:";
        Strings.in = "shake:";
        Strings.ic = "shake:";
        Strings.ii = "scroll:";
        Strings.ik = "scroll:";
        Strings.ie = "slide:";
        Strings.iq = "slide:";
        Strings.iv = "RuneScape is loading - please wait...";
        Strings.ir = "";
        Strings.io = "Enter your username/email & password.";
        Strings.ip = "";
        Strings.im = "Warning!";
        Strings.ij = "This is a <col=ff0000>PvP<col=ffffff> world.";
        Strings.id = "Players can attack each other";
        Strings.it = "almost everywhere.";
        Strings.ix = "This is a <col=ffff00>High Risk<col=ffffff> world.";
        Strings.ib = "The Protect Item prayer will";
        Strings.jc = "not work on this world.";
        Strings.ji = "This is a <col=ffff00>High Risk <col=ff0000>PvP<col=ffffff> world.";
        Strings.jg = "Players can attack each other almost everywhere";
        Strings.jx = "and the Protect Item prayer won't work.";
        Strings.jo = "This is a <col=00ffff>Beta<col=ffffff> world.";
        Strings.jk = "Your normal account will not be affected.";
        Strings.jq = "";
        Strings.je = "Authenticator";
        Strings.jj = "<u=ff>Can't Log In?</u>";
        Strings.jm = "";
        Strings.jn = "Connecting to server...";
        Strings.jd = "";
        Strings.jf = "The game servers are currently being updated.";
        Strings.jw = "Please wait a few minutes and try again.";
        Strings.js = "";
        Strings.jr = "";
        Strings.jv = "You were disconnected from the server.";
        Strings.jh = "";
        Strings.jy = "Login: ";
        Strings.jp = "Password: ";
        Strings.jt = "PIN: ";
        Strings.ja = "Welcome to RuneScape";
        Strings.jb = "New User";
        Strings.jz = "Existing User";
        Strings.ju = "Login";
        Strings.jl = "Cancel";
        Strings.kc = "Remember username";
        Strings.ku = "Hide username";
        Strings.ke = "Incorrect username or password.";
        Strings.ky = "If you have upgraded to a Jagex Account, you";
        Strings.kh = "need to log in using the <u=ffd200><col=ffd200>Jagex Launcher</col></u> instead.";
        Strings.kp = "Try again";
        Strings.kf = "Forgotten password?";
        Strings.ks = "Forgotten your password?";
        Strings.kn = "Username/email: ";
        Strings.kz = "Recover";
        Strings.km = "Back";
        Strings.lv = "Can't login? Click here.";
        Strings.lm = "Still having trouble logging in?";
        Strings.lg = "Having trouble logging in?";
        Strings.ls = "";
        Strings.lf = "Page has opened in the browser.";
        Strings.li = "";
        Strings.lu = "Please enter your username.";
        Strings.lk = "If you created your account after November";
        Strings.lh = "2010, this will be the creation email address.";
        Strings.field3267 = Strings.ls;
        Strings.field3291 = Strings.lf;
        Strings.field3376 = Strings.li;
        Strings.ln = "";
        Strings.lt = "Error connecting to server.";
        Strings.lz = "";
        Strings.lc = "The part of the website you are trying";
        Strings.ld = "to connect to is offline at the moment.";
        Strings.lq = "Please try again later.";
        Strings.lj = "Sorry, there was an error trying to";
        Strings.ll = "log you in to this part of the website.";
        Strings.le = "Please try again later.";
        Strings.lb = "";
        Strings.lx = "Error connecting to server.";
        Strings.lo = "";
        Strings.lw = "You must enter a valid login to proceed. For accounts";
        Strings.lr = "created after 24th November 2010, please use your";
        Strings.mt = "email address. Otherwise please use your username.";
        Strings.mw = "Your date of birth isn't set.";
        Strings.mz = "Please verify your account status by";
        Strings.mu = "setting your date of birth.";
        Strings.mq = "Set Date of Birth";
        Strings.mm = "Your date of birth information is waiting";
        Strings.me = "to be reviewed by our staff.";
        Strings.mv = "It will be processed shortly.";
        Strings.mx = "Before using this app, please read and accept our";
        Strings.ma = "<col=ffd200>terms of use</col>, <col=ffd200>privacy policy</col>, and <col=ffd200>end user licence</col>";
        Strings.mp = "<col=ffd200>agreement (EULA)</col>.";
        Strings.mj = "By accepting, you agree to these documents.";
        Strings.ms = "You must accept our terms of use, privacy policy,";
        Strings.mc = "and end user licence agreement to continue.";
        Strings.mh = "Accept";
        Strings.mg = "Decline";
        Strings.mo = "Select a world";
        Strings.mn = "Members only world";
        Strings.mi = "Free world";
        Strings.md = "World";
        Strings.mr = "Players";
        Strings.ml = "Location";
        Strings.mf = "Type";
        Strings.my = "OFF";
        Strings.mk = "FULL";
        Strings.mb = "Loading...";
        Strings.nz = "Click to switch";
        Strings.nw = "Download Launcher";
        Strings.ns = "https://oldschool.runescape.com/launcher";
    }
    
    public static void method1854(final int n) {
        try {
            WorldMapElement.WorldMapElement_cachedSprites.clear();
        }
        catch (RuntimeException ex) {
            throw HealthBar.get(ex, "mk.at(" + ')');
        }
    }
    
    static IndexedSprite method1852(final byte b) {
        try {
            final IndexedSprite indexedSprite = new IndexedSprite();
            indexedSprite.subHeight = -822007097 * class503.SpriteBuffer_spriteWidth;
            indexedSprite.width = class503.SpriteBuffer_spriteHeight * 378525975;
            indexedSprite.height = class503.SpriteBuffer_xOffsets[0];
            indexedSprite.xOffset = class17.SpriteBuffer_yOffsets[0];
            indexedSprite.yOffset = class97.SpriteBuffer_spriteWidths[0];
            indexedSprite.subWidth = class138.SpriteBuffer_spriteHeights[0];
            indexedSprite.palette = class394.SpriteBuffer_spritePalette;
            indexedSprite.pixels = VarbitComposition.SpriteBuffer_pixels[0];
            class398.method2125(-262861184);
            return indexedSprite;
        }
        catch (RuntimeException ex) {
            throw HealthBar.get(ex, "mk.al(" + ')');
        }
    }
    
    public static final SpritePixels method1853(final byte[] buf, final int n) {
        try {
            BufferedImage read = null;
            try {
                synchronized (ImageIO.class) {
                    read = ImageIO.read(new ByteArrayInputStream(buf));
                }
                final int width = read.getWidth();
                final int height = read.getHeight();
                final int[] pix = new int[width * height];
                new PixelGrabber(read, 0, 0, width, height, pix, 0, width).grabPixels();
                return new SpritePixels(pix, width, height);
            }
            catch (IOException ex2) {}
            catch (InterruptedException ex3) {}
            return new SpritePixels(0, 0);
        }
        catch (RuntimeException ex) {
            throw HealthBar.get(ex, "mk.af(" + ')');
        }
    }
}
