name: Publish Client Update

on:
  push:
    branches:
      - main

jobs:
  check_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Fetch two commits to compare changes

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check if version in gradle.properties has changed
        id: check_version_change
        run: |
          if git diff HEAD~1 HEAD -- gradle.properties | grep -q '^+version='; then
            echo "Version has changed"
            echo "version_changed=true" >> $GITHUB_ENV
          else
            echo "Version has not changed"
            echo "version_changed=false" >> $GITHUB_ENV
          fi

      - name: Check if Configuration is LOCAL
        id: check_configuration
        run: |
          if grep -q "public static Connection CONNECTION = Connection.LOCAL;" src/main/java/com/client/Configuration.java; then
            echo "Configuration is LOCAL"
            echo "is_local=true" >> $GITHUB_ENV
          else
            echo "Configuration is not LOCAL"
            echo "is_local=false" >> $GITHUB_ENV
          fi
        if: env.version_changed == 'true'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        if: env.version_changed == 'true'

      - name: Perform Gradle Task publishClientLive if not LOCAL
        if: env.is_local == 'false' && env.version_changed == 'true'
        run: ./gradlew publishClientLive
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

      - name: Upload Ark-Client files
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: ark-client-files
          path: /home/runner/.local/share/Ark-Client/
